import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from '@/components/Sidebar'
import ModalProvider from '@/providers/ModalProvider'
import SessionProvider from '@/providers/SessionProvider'
import { getServersideSession } from '@/lib/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServersideSession();
  return (
    <html lang="en">
      <body className={inter.className + " bg-black text-white"}>
        <SessionProvider session={session}>
          <ModalProvider />
          <Sidebar>
            {children}
          </Sidebar>
        </SessionProvider>
      </body>
    </html>
  )
}
